apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: album

images:
- name: imagem
  newName: blgianini/humix
  newTag: 48b666c5e560f8fef9f4610b34c6edaeb5fe5d79
